### ISSUE TITLE
Make the blossom location clickable

### ISSUE THREAD

**Issue by begeeben** [sideroad/floras#1]
It would be very helpful to get the blossom location information on mouse click.

**Comment by sideroad** [comment]
Yes! I'm plan to display below.
- Place name
- Place photos from instagram. ( refer seasonally tag as well )
- Seasonal graph
- Link to display on original google map

**Comment by sideroad** [comment]
Implemented!

**Comment by sideroad** [comment]
thanks to suggest flickr
