### ISSUE TITLE
It always shows scrollbar.

### ISSUE THREAD

**Issue by john-hu** [sideroad/floras#2]
The scrollbar shouldn't appear in this case:

![screen shot 2017-02-17 at 1 52 50 pm](https://cloud.githubusercontent.com/assets/6179015/23054077/98328d3e-f518-11e6-919a-13c2370bfb44.png)

If using mac, we may not notice this issue. But it is easy to find at window or linux box.

**Comment by sideroad** [comment]
Thanks for reporting!
It might be fixed by commit below.

https://github.com/sideroad/four-seasons/commit/838beda7d2c51533c9a30a8750bb40a8a8ccfc5b#diff-e90cf483076ab24ed20ee047b1988262
